name: e_warong
version: 1.1.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animated_splash_screen: ^1.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  line_icons: ^2.0.1
  liquid_pull_to_refresh: 3.0.1
  page_transition: ^2.0.5
  timeago: ^3.2.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2-Regular.ttf
        - asset: assets/fonts/Baloo2-Bold.ttf
          weight: 700

  uses-material-design: true
